### ISSUE TITLE
Lab 06/Exercise 3: mistranslation

### ISSUE THREAD

**Issue by yokoyama-tetsuya** [MicrosoftLearning/AZ500-AzureSecurityTechnologies.ja-jp#1]
# Module: 01
#### Step: 09

Description of issue
mistranslation
English ver
leave all optional configuration options **deselected** and click Install.

Japanease ver
「必須コンポーネントのインストール」ページで、オプションの構成オプションをすべて**選択した**ままにして、「インストール」をクリックします。
note:
「選択した(means "selected")」 should change to 「解除した(means "deselected")」

The sentense should be the following
「必須コンポーネントのインストール」ページで、オプションの構成オプションをすべて**解除した**ままにして、「インストール」をクリックします。

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
The locfile status in Handedback, waiting for check In and then I will fix it.  [ICMS QUERY](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=C%26E&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5GYWxzZTwvU0hSUD48U0FUTz5GYWxzZTwvU0FUTz48U0FMTz5UcnVlPC9TQUxPPjxRRT4%2bMjwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO0xBQl9BWjUwMDwvUVI%2bPFFSIElkPSIyIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtMb2NGaWxlcztMYW5ndWFnZTtFcXVhbDtKYXBhbmVzZSAoSmFwYW4pPC9RUj48UVIgSWQ9IjMiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgRmlsZSBSZWZlcmVuY2U7RXF1YWw7aHR0cHM6Ly9naXRodWIuY29tL01pY3Jvc29mdExlYXJuaW5nL0FaNTAwLUF6dXJlU2VjdXJpdHlUZWNobm9sb2dpZXMvYmxvYi9tYXN0ZXIvSW5zdHJ1Y3Rpb25zL0xhYnMvTEFCXzA2X0ltcGxlbWVudERpcmVjdG9yeVN5bmNocm9uaXphdGlvbi5tZDwvUVI%2bPC9RVD48Ukc%2bPEdDPk5VTEw8L0dDPjwvUkc%2bPC9WUFE%2b)

**Comment by stonezy123** [comment]
Run bugfix tool and waiting for result.

**Comment by olprod** [comment]
![image](https://user-images.githubusercontent.com/16075726/185302014-1ed1fba5-7576-46ad-b395-fada013fc982.png)
