### ISSUE TITLE
Lab 11 is the same as Lab 08

### ISSUE THREAD

**Issue by yokoyama-tetsuya** [MicrosoftLearning/AZ500-AzureSecurityTechnologies.ja-jp#13]
# <a name="module-11"></a>モジュール: 04
## <a name="labdemo-11"></a>ラボ/デモ:11

懸案事項の説明
以下の2つの演習は同じ作業をしている。LAB 11は不要
Instructions/Labs/LAB_08_Azure Monitor.md
Instructions/Labs/LAB_11_Azure Monitor.md

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
Remove the Instructions/Labs/LAB_11_Azure Monitor.md
