### ISSUE TITLE
演習指示と画面が違う

### ISSUE THREAD

**Issue by yokoyama-tetsuya** [MicrosoftLearning/AZ500-AzureSecurityTechnologies.ja-jp#2]
# <a name="lab-04-mfa-conditional-access-and-aad-identity-protection"></a>ラボ 04:MFA、条件付きアクセス、AAD ID 保護
#### <a name="step-00"></a>ステップ:5
**[Users or workload identities selected](選択されているユーザーまたはワークロード ID)** をクリックします。

懸案事項の説明
画面に合わせて、以下のとおり変更して欲しい

**[ユーザーとグループの選択]** を選択します。

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
[Locfile](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5UcnVlPC9TSFJQPjxTQVRPPlRydWU8L1NBVE8%2bPFNBTE8%2bRmFsc2U8L1NBTE8%2bPFFFPj4yPC9RRT48UVQ%2bPjxRUiBJZD0iMSIgQ1BJRD0iMCI%2bQ3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgU3RvcmU7RXF1YWw7V1dMPC9RUj48UVIgSWQ9IjIiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgQXNzZXQgSUQ7RXF1YWw7TEFCXzA0X01GQUNvbmRpdGlvbmFsQWNjZXNzYW5kQUFESWRlbnRpdHlQcm90ZWN0aW9uLm1kPC9RUj48UVIgSWQ9IjMiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0xvY0ZpbGVzO0xhbmd1YWdlO0VxdWFsO0phcGFuZXNlIChKYXBhbik8L1FSPjwvUVQ%2bPFJHPjxHQz5OVUxMPC9HQz48L1JHPjwvVlBRPg%3d%3d) to update

**Comment by chriscarty00** [comment]
Locfile updated and uploaded
