### ISSUE TITLE
指示が分かりにくい

### ISSUE THREAD

**Issue by yokoyama-tetsuya** [MicrosoftLearning/AZ500-AzureSecurityTechnologies.ja-jp#4]
# <a name="lab-04-mfa-conditional-access-and-aad-identity-protection"></a>ラボ 04:MFA、条件付きアクセス、AAD ID 保護
#### <a name="task-5-configure-azure-mfa-settings"></a>タスク 5:Azure MFA 設定を構成します。

10. **[キャンセル]** をクリックし、Azure portal の **[多要素認証 \| はじめに]** ブレードが表示されているブラウザー タブに戻ります。

懸案事項の説明
キャンセルをクリックしたあとの操作が分かりにくい。
以下のように変更して欲しい。

10. **[キャンセル]** をクリックします。 **[AdatumLab500-04]** ブレードの **[管理]** セクションで **[セキュリティ]** をクリックし、さらに **[管理]** セクションの **[多要素認証]** をクリックして **[多要素認証 \| はじめに]** ブレードに切り替えます。

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
[Locfiles ](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5UcnVlPC9TSFJQPjxTQVRPPlRydWU8L1NBVE8%2bPFNBTE8%2bRmFsc2U8L1NBTE8%2bPFFFPj4yPC9RRT48UVQ%2bPjxRUiBJZD0iMSIgQ1BJRD0iMCI%2bQ3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgU3RvcmU7RXF1YWw7V1dMPC9RUj48UVIgSWQ9IjIiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgQXNzZXQgSUQ7RXF1YWw7TEFCXzA0X01GQUNvbmRpdGlvbmFsQWNjZXNzYW5kQUFESWRlbnRpdHlQcm90ZWN0aW9uLm1kPC9RUj48UVIgSWQ9IjMiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0xvY0ZpbGVzO0xhbmd1YWdlO0VxdWFsO0phcGFuZXNlIChKYXBhbik8L1FSPjwvUVQ%2bPFJHPjxHQz5OVUxMPC9HQz48L1JHPjwvVlBRPg%3d%3d)

**Comment by chriscarty00** [comment]
Proposed changes would need to be reflected in the en-us file so it could be taken for all loc languages

**Comment by stonezy123** [comment]
The locfile was updated and this issue was too old, if still repo, please help create new one. thanks.
https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies.ja-jp/blob/main/Instructions/Labs/LAB_04_ConfiguringandSecuringACRandAKS.MD
