### ISSUE TITLE
Translation Updates Lab 02

### ISSUE THREAD

**Issue by Universo-Ap00** [MicrosoftLearning/AZ500-AzureSecurityTechnologies.ja-jp#5]
Lab 6

名前 should be "First name" 

Replacing these characters with "First name" for one specified location changes fields in many other locations. Be best to do this one edit into instructions themselves manually.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
N/A as page has changed
