### ISSUE TITLE
mssing access policy for key vault

### ISSUE THREAD

**Issue by yokoyama-tetsuya** [MicrosoftLearning/AZ500-AzureSecurityTechnologies.ja-jp#6]
# <a name="Lab 10"></a>LAB 10: Key Vault
#### <a name="step-09"></a>ステップ:09

ラボ10
演習 2:キーとシークレットを使用して Key Vaultのリソースを構成する
タスク 1:Key Vaultを作成して構成する
9. [アクセス ポリシーの作成] ブレードで、次の設定を指定します (他の設定はすべて既定値のままにします)。

設定: キーのアクセス許可
[すべて選択] をクリックすると、アクセス許可が 12 個選択されます ( [ポリシーのローテーション操作] のアクセス許可がオフになっていることを確認します)

issue: 以下の追加手順が必要
[暗号化操作]の[すべて選択]をクリックすると、アクセス許可が 6 個選択されます

**Comment by dakozu** [comment]
Hello @chriscarty00, 
Already English content was updated for fixing same issue. Please confirm it.
https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies/commit/0420a3fb7b74e457e04251f8ade239e700e72ab5

**Comment by chriscarty00** [comment]
We would need to update the locfiles for this - HO would be turned off here and would be ondemand.

**Comment by chriscarty00** [comment]
![image](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies.ja-jp/assets/63402128/905d5600-ddac-482d-8c54-b3203d1287b5)

![image](https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies.ja-jp/assets/63402128/4dca0aab-6985-4da9-953d-e1061f746ea3)

**Comment by chriscarty00** [comment]
Loc Matches the US now - I am not a lang expert but this seems ok now
